prebuilt_cxx_library(
  name = 'pthread',
  header_only = True,
  exported_linker_flags = [
    '-lpthread',
  ],
)

cxx_library(
    name = 'ff_headers',
    exported_headers = subdir_glob([
        ('include/ff', '**/*.h'),
    ]),
    visibility = ['PUBLIC']
)

cxx_binary(
    name = 'ff',
    srcs = [
        'ff.cpp',
    ],
    deps = [
        ':ff_headers',
        ':pthread',
    ],
    compiler_flags = [
        '-Ideps/libgflags/include',
    ],
)
